name: tag-release

# only runs on main push AFTER full ci lint/test/build job matrix completes.
on:
  workflow_run:
    workflows:
      - lint-test-build
    branches:
      - main
    types:
      - completed

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # pull all tags also
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"      
      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: tox cache
        id: tox-cache
        uses: actions/cache@v2
        with:
          path: .tox
          key: ${{ runner.os }}-tox-${{ hashFiles('tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-tox-

      - name: run tag pipeline.
        uses: pypyr/run-in-tox-action@main
        with:
          pipeline: ops/tag